version: '3.6'
services:
  clozet-postgres:
    image: postgres:13
    ports:
      - '5932:5432' # expose pg on port 5932 to not collide with pg from elsewhere
    restart: always
    env_file: ".env"
    volumes:
      - clozet_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  clozet_db_data:
